name: Releases

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
          - x86_64-pc-windows-msvc
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: x86_64-pc-windows-msvc
            os: windows-latest

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Build asset
        run: ci/make-release-asset.sh ${{ matrix.os }} ${{ matrix.target }}
      - name: Update release with new asset
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
        run: gh release upload $TAG $ASSET
