name: Releases

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Release
        run: cargo build --release
      - name: Package
        working-directory: .
        run: tar -zcvf helloworld-${{ matrix.os }}.tar.gz -C target/release hello_world
      - name: Update release with new asset
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_GITHUB_TOKEN }}
        run: gh release upload ${{ steps.get_version.outputs.VERSION }} helloworld-${{ matrix.os }}.tar.gz
